### ISSUE TITLE
hremd continuation

### ISSUE THREAD

**Issue by Dan-Burns** [Psivant/femto#2]
Quick question about restarting an hremd.  I would normally restart a standard simulation with a checkpoint file.  With remd the kinetics are lost so as long as the systems are restarted with appropriate velocities for their effective temperatures, it probably isn't necessary to use checkpoint file.  How would you suggest continuing a simulation?  Extract the coordinates from each replica from their last frames and supply them as `initial_coords' to `run_hremd`?

It looks like the replica trajectories are continuous so to get the correct ensemble for each temperature, the frames will have to be shuffled according to the records in the arrow file?

Would `states` then have to be provided to `run_hremd` in the order according to the last state that each replica was at?

Thank you.

**Comment by SimonBoothroyd** [comment]
@Dan-Burns `run_hremd` now returns `u_kn, n_k, final_coords` so should be easier to restart from these. in addition, i [added a basic checkpointing system](https://github.com/Psivant/femto/pull/6). hope this helps!
